# Introvert vs Extrovert Analysis

In [3]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Load the dataset
df = pd.read_csv('../data/personality_datasert.csv')

print(f"The dataset has {df.shape[0]} rows and {df.shape[1]} columns.")

The dataset has 2900 rows and 8 columns.

In [5]:
# Display the first 10 rows of the dataset
df.head(10)

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,4.0,No,4.0,6.0,No,13.0,5.0,Extrovert
1,9.0,Yes,0.0,0.0,Yes,0.0,3.0,Introvert
2,9.0,Yes,1.0,2.0,Yes,5.0,2.0,Introvert
3,0.0,No,6.0,7.0,No,14.0,8.0,Extrovert
4,3.0,No,9.0,4.0,No,8.0,5.0,Extrovert
5,1.0,No,7.0,5.0,No,6.0,6.0,Extrovert
6,4.0,No,9.0,3.0,No,7.0,7.0,Extrovert
7,2.0,No,8.0,4.0,No,7.0,8.0,Extrovert
8,10.0,Yes,1.0,3.0,Yes,0.0,3.0,Introvert
9,0.0,No,8.0,6.0,No,13.0,8.0,Extrovert

In [6]:
# Data types and missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2900 entries, 0 to 2899
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Time_spent_Alone           2900 non-null   float64
 1   Stage_fear                 2900 non-null   str
 2   Social_event_attendance    2900 non-null   float64
 3   Going_outside              2900 non-null   float64
 4   Drained_after_socializing  2900 non-null   str
 5   Friends_circle_size        2900 non-null   float64
 6   Post_frequency             2900 non-null   float64
 7   Personality                2900 non-null   str
dtypes: float64(5), str(3)
memory usage: 181.4 KB

We can see from the Non-Null Count that there is no missing values in this dataset.

In [ ]:
# Statistical summary of the numerical columns
df.describe().round(2)

,Time_spent_Alone,Social_event_attendance,Going_outside,Friends_circle_size,Post_frequency
count,2900.00,2900.00,2900.00,2900.00,2900.00
mean,4.51,3.96,3.00,6.27,3.56
std,3.44,2.87,2.22,4.23,2.89
min,0.00,0.00,0.00,0.00,0.00
25%,2.00,2.00,1.00,3.00,1.00
50%,4.00,3.96,3.00,5.00,3.00
75%,7.00,6.00,5.00,10.00,6.00
max,11.00,10.00,7.00,15.00,10.00

In [8]:
# Check for duplicate rows
dp_rows = df[df.duplicated()]
print(f"Number of duplicate rows: {len(dp_rows)}")

Number of duplicate rows: 402